[location_nodes]
node1 ansible_host=192.168.80.80 ansible_user=felkru ansible_ssh_private_key_file=~/.ssh/id_rsa_ansible_caish lat=52.2066 lng=0.1202 anchor_port=8924
tuusula ansible_host=37.27.88.255 ansible_user=ryanb ansible_ssh_private_key_file=~/.ssh/id_rsa_ansible_caish lat=60.4000 lng=25.0000 anchor_port=8925
falkenstein ansible_host=167.235.203.200 ansible_user=ryanb ansible_ssh_private_key_file=~/.ssh/id_rsa_ansible_caish lat=50.2163 lng=8.4510 anchor_port=8926